version: "3.5"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus
    #volumes:
    #  - /prometheus:/tmp/prometheus/
    command:
      - '--config.file=/tmp/prometheus/prometheus.yml'
    ports:
      - 9380:9090
    restart: unless-stopped
  spring-admin:
    build: ./spring-admin/
    ports:
      - 9280:8080
  spothero:
    build: ./
    depends_on:
      - spring-admin
    ports:
      - 8280:8080
      - 8281:8081